export const featuredCollection = [
  {
    id: 1,
    name: "Ani Mkhitaryan",
    floorPrice: "0.05 ETH",
    img: "https://i.seadn.io/gcs/files/522f76d60d0ccc374011c1092145fd74.jpg?auto=format&w=1920",
    verified: true,
  },
  {
    id: 2,
    name: "Math Art (1980-1995) by Herbert W. Franke",
    floorPrice: "0.15 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/Math%20Art%20Herbert%20W%20Franke.png?auto=format&w=1920",
    verified: false,
  },
  {
    id: 3,
    name: "Neko Nation",
    floorPrice: "0.04 ETH",
    img: "https://i.seadn.io/gcs/files/6b26e80ca71ea9c7127bcc31149931d6.jpg?auto=format&w=1920",
    verified: true,
  },
  {
    id: 4,
    name: "Diplo - Don't Forget My Love",
    floorPrice: "",
    img: "https://i.seadn.io/gcs/static/promocards/Diplo.png?auto=format&w=1920",
    verified: false,
  },
  {
    id: 5,
    name: "Streets by esraeslen",
    floorPrice: "0.17 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/Streets.png?auto=format&w=828",
    verified: false,
  },
  {
    id: 6,
    name: "Ometti",
    floorPrice: "0.04 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/Ometti.png?auto=format&w=828",
    verified: false,
  },
  {
    id: 8,
    name: "E4C Rangers Ultimate Edition",
    floorPrice: "19 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/E4CRangers.png?auto=format&w=828",
  },
  {
    id: 9,
    name: "LofiLofts",
    floorPrice: "0.02 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/LofiLofts.png?auto=format&w=828",
    verified: true,
  },
  {
    id: 10,
    name: "ArtWork by OllOOl",
    floorPrice: "0.17 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/ArtWork%20by%20OllOOl.png?auto=format&w=828",
  },
  {
    id: 11,
    name: "The Ladies",
    floorPrice: "1 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/The%20Ladies.png?auto=format&w=828",
    verified: true,
  },
  {
    id: 12,
    name: "Lumens by Vibes + Logic",
    floorPrice: "0.05 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/Lumens%20by%20Vibes%20%2B%20Logic.png?auto=format&w=828",
    verified: true,
  },
  {
    id: 13,
    name: "SAN Origin",
    floorPrice: "0.05 ETH",
    img: "https://i.seadn.io/gcs/static/promocards/SAN%20Origin.png?auto=format&w=828",
    verified: false,
  },
];
